baseURL: "https://kevinpatel.xyz/"
title: Kevin Patel
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: KevinPatel
  description: "Kevin's Personal Site"
  keywords: [Posts, Projects, Home]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  #    ShowReadingTime: true
  #    ShowShareButtons: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/favicon-32x32.png"

  label:
    text: "Kevin Patel"
    iconHeight: 35

  profileMode:
    enabled: true # needs to be explicitly set
    title: Kevin Patel
    subtitle: "Software Developer @ NISC | Security Enthusiast"
    imageUrl: "/profile.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Profile Picture

  socialIcons:
    - name: twitter
      url: "https://twitter.com/kevinpatel35"
    - name: linkedin
      url: "https://www.linkedin.com/in/kevinpatel75/"
    - name: github
      url: "https://github.com/CyberT17"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
    appendFilePath: true # to append file path to Edit link

menu:
  main:
    # Add a new Main path using "hugo new [name]"
    # Add a single page using "hugo new [path name]/filename.md"
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 20
